### ISSUE TITLE
Host documentation

### ISSUE THREAD

**Issue by kvark** [gfx-rs/metal-rs#5]
Most of the project rely on `docs.rs` for documentation, however it only builds Linux at the moment. We need to find a good way of providing the documentation here.

cc @fkaa @JohnColanduoni

**Comment by kvark** [comment]
Related - https://github.com/onur/docs.rs/pull/73

**Comment by mjadczak** [comment]
Also related to this: https://github.com/onur/docs.rs/issues/93

**Comment by IsaccBarker** [comment]
I know this is a really old issue, but I found a way to do it with GitHub's new Actions to Pages functionality. Below is an example, and you can find [working documentation hosted on my fork.](https://github.com/IsaccBarker/metal-rs):

```yaml
name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Document
      run: cargo doc --verbose
#    - name: Packaging
#      run: tar -zcvf github-pages.tar.gz ./target/doc
    - name: Packaging
      run: mv target/doc _site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
You have to set it up in the repository settings though.
